# Generated by Django 3.0.3 on 2020-08-28 11:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя Telegram')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя Telegram')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Фотография')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер участника')),
                ('photo_lips_face_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с губами до')),
                ('photo_lips_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото губ до')),
                ('photo_lips_face_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с губами после')),
                ('photo_lips_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото губ после')),
                ('photo_eyeline_face_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с веками до')),
                ('photo_eyeline_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото век до')),
                ('photo_eyeline_face_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с веками после')),
                ('photo_eyeline_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото век после')),
                ('photo_brows_face_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с бровями до')),
                ('photo_brows_before', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото бровей до')),
                ('photo_brows_face_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото лица с бровями после')),
                ('photo_brows_after', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото бровей после')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Акварельные губы'), (1, 'Веки с растушевкой'), (2, 'Пудровые брови')], verbose_name='Номинация')),
                ('marks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]), size=None, verbose_name='Оценки')),
                ('message', models.TextField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Judge', verbose_name='Судья')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant', verbose_name='Участник')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True, verbose_name='Идентификатор чата')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant', verbose_name='Участник')),
            ],
        ),
    ]
