# Generated by Django 2.2.4 on 2019-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190827_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='number',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='telegram_username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
