# Generated by Django 2.2.4 on 2019-08-28 20:19

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190827_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', django.contrib.postgres.fields.hstore.HStoreField()),
                ('judge_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Judge')),
                ('participant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant')),
            ],
        ),
    ]
