# Generated by Django 2.2.4 on 2019-08-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rating',
        ),
    ]
