# Generated by Django 2.2.4 on 2019-08-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20190828_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='judge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Judge'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant'),
        ),
    ]
