# Generated by Django 2.2.4 on 2019-08-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20190829_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='judge_id',
            new_name='judge',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
