# Generated by Django 2.2.4 on 2019-09-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20190829_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Participant')),
            ],
        ),
    ]
